### ISSUE TITLE
'module' object has no attribute 'SIGTRAP'

### ISSUE THREAD

**Issue by gtalarico** [tamentis/rpdb#22]
Running this on Python 2.7 win32, getting the traceback below.
Is this library not windows compliant?

```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
>>> import rpdb
>>> rpdb.handle_trap()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gtalarico\.env\testpy2\lib\site-packages\rpdb\__init__.py", line 125, in handle_trap
    signal.signal(signal.SIGTRAP, partial(_trap_handler, addr, port))
AttributeError: 'module' object has no attribute 'SIGTRAP'
```

```
>>> #missing sigtrap
>>> dir(signal)
['CTRL_BREAK_EVENT', 'CTRL_C_EVENT', 'NSIG', 'SIGABRT', 'SIGBREAK', 'SIGFPE', 'SIGILL', 'SIGINT', 'SIGSEGV', 'SIGTERM', 'SIG_DFL', 'SIG_IGN', '__doc__', '__name__', '__package__', 'default_int_handler', 'getsignal', 'set_wakeup_fd', 'signal']
>>>
```

**Comment by seandst** [comment]
SIGTRAP isn't available on Windows:
https://docs.python.org/2/library/signal.html#signal.signal

The library should work fine on Windows; you'll just need to implement a "Windows compliant" mechanism for firing `set_trace()` on some external action that works on that platform.

**Comment by gtalarico** [comment]
Thank you!
